### ISSUE TITLE
Add option to use AWS Signature Version 4/support for new AWS locations

### ISSUE THREAD

**Issue by padde** [danilop/yas3fs#101]
Newer AWS locations (in my case Frankfurt) will only authenticate clients that use AWS Signature Version 4. It would be nice to have it as an option, because these newer locations are unusable otherwise. SigV4 seems to require an explicit S3 host parameter so this would have to be added as a command line option, too. My suggestion is to introduce a `--s3-host` flag. If set, SigV4 should automatically be used. Alternatively a new `--s3-sigv4` flag could be used to make this more explicit.

It seems that older locations all support SigV4 so it should not be a problem to be compatible with those. Maybe users of these older locations will benefit from SigV4 as well as it promises to provide increased security and performance, but I didn't research that any further. I am just trying to get this to work with an S3 bucket in Frankfurt.

Apparently, enabling SigV4 with boto requires two changes. First, you need to set `os.environ['S3_USE_SIGV4'] = 'True`. Second, you need to set the host parameter when calling `S3Connection()`, or `boto.connect_s3()`, respectively. Also see https://github.com/boto/boto/issues/2741

I'm a complete Python noob so I may not be the most suitable person to make a PR for this, but I can give it a try if no one else has the time.

**Comment by danilop** [comment]
I never tested yas3fs with Frankfurt, but I know of the SigV4 requirement. If you implement what you described. that would be awesome!

**Comment by padde** [comment]
Thanks for your comments. I've already created a PR, it would be great if you could take a look!

**Comment by padde** [comment]
Note that I called the flag `--s3-endpoint` instead of `--s3-host` because that's the nomenclature that Amazon use in their docs: http://docs.aws.amazon.com/general/latest/gr/rande.html
