### ISSUE TITLE
Can multiple mounts occur on one node?

### ISSUE THREAD

**Issue by matthewlehew** [danilop/yas3fs#126]
For example, on a server where multiple virtual hosts need to mount different paths in the same S3 bucket? In this scenario, the messaging aspect wouldn't need to be used, either, since there is a 1 to 1 relationship between virtual hosts and mounted directories.

**Comment by matthewlehew** [comment]
The answer is yes. :)

**Comment by davetbo** [comment]
One follow-up on this topic:
I am mounting 2 different folders in the same bucket to 2 different mount points:
bucket1/folder1 => /var/www/html/wp-content/uploads
bucket1/folder2 => /var/www/protected-files
I'm doing this from multiple web servers to the same bucket (to sync my wp uploads across my various clustered web servers).

In this instance, can I use the same topic, queue, and cachedir, or should I have different ones for each mount point?

Thanks,
Dave
