### ISSUE TITLE
SQS queues created with --new-queue are not being deleted when unmounting with fusermount -u

### ISSUE THREAD

**Issue by tonnydourado** [danilop/yas3fs#14]
The help says that the --new-queue parameter creates a queue that's deleted on umount, but this is not happening for me. The queues keep showing on the SQS panel, after either killing the process or unmounting with fusermount -u (which also terminates the process). Does it just take some time to then to disappear, like terminated EC2 instances, or there's something wrong here?

**Comment by jazzl0ver** [comment]
Faced the same issue during shutdown. Things stopped here:
```
MainThread 2018-10-02T05:38:57.744 INFO waiting for SQS listen thread to shutdown...
```
@danilop, what did you mean by "short time-out"? Which timeout value should be increased?

**Comment by tonnydourado** [comment]
Just so you know, I'm not using yas3fs anymore, so, can't help debugging or confirming stuff anymore. Good luck, though =)

**Comment by jazzl0ver** [comment]
@tonnydourado did you find a substitution or just you don't need it anymore?

**Comment by tonnydourado** [comment]
@jazzl0ver Not working in the project where I used it anymore.

**Comment by jazzl0ver** [comment]
This happens b/c unmounting a fuse device does not wait for the completeness. This is a known issue: https://github.com/libfuse/libfuse/issues/1
