### ISSUE TITLE
SNS/SQS Notification system is susceptible to badly formatted messages

### ISSUE THREAD

**Issue by JochiPochi** [danilop/yas3fs#141]
I've observed this on 2.3.2.  When a badly formatted SNS message is sent to a topic, all the yas3fs cluster nodes listening to that topic display a decode error.Then they stop listening to any future SNS messages until yas3fs is restarted.

This makes the notification services brittle. The more publishers to the SNS topic, the more probability of this happening. Specially if some of those are not yas3fs instances. (Lambda functions, etc)

I have not yet tested with the latest release but I will when I get time. I wanted to document this behavior first so I wouldn't forget about it though.

**Comment by Liath** [comment]
Just created a PR for this. Thanks for reporting it. :)
