### ISSUE TITLE
New AWS region: eu-west-2

### ISSUE THREAD

**Issue by ollietreend** [danilop/yas3fs#143]
Hi,

I'm trying to use `yas3fs` with the new AWS region `eu-west-2`.

Unfortunately `yas3fs` fails to start, with the error message:

```
ERROR wrong AWS region 'eu-west-2' for S3, use -h for help.
```

It looks like this is caused due to the new region not existing in `boto.s3.regions()`'s list of regions. From [\_\_init\_\_.py lines 848-849](https://github.com/danilop/yas3fs/blob/774426041850155185ce64fb1746a3daedf61230/yas3fs/__init__.py#L848-L849):

```python
if not self.aws_region in (r.name for r in boto.s3.regions()):
    error_and_exit("wrong AWS region '%s' for S3" % self.aws_region)
```

I'm not a python guy, but it looks as if `boto` has been deprecated in favour of [`boto3`](https://github.com/boto/boto3). Is there anything we can do to add support for those new regions into `yas3fs`?

**Comment by reiven** [comment]
Hi @ollietreend looks like you're running an older boto version

>  pprint(boto.s3.regions())
[RegionInfo:us-east-1,
 RegionInfo:us-west-1,
 RegionInfo:cn-north-1,
 RegionInfo:ap-northeast-1,
 RegionInfo:ap-southeast-2,
 RegionInfo:sa-east-1,
 RegionInfo:ap-southeast-1,
 RegionInfo:ap-northeast-2,
 RegionInfo:us-west-2,
 RegionInfo:us-gov-west-1,
 RegionInfo:ap-south-1,
 RegionInfo:eu-central-1,
 RegionInfo:eu-west-1,
 RegionInfo:us-east-2]

Check your boto version with pip freeze

> $ pip freeze | grep boto
boto==2.43.0
boto3==1.4.1
botocore==1.4.78

I suggest you to run 

> $ pip install -U boto


Are you running on virtualenv?

**Comment by ollietreend** [comment]
Thanks @reiven! Upgrading `boto` did the trick.

I'm not familiar with python, so didn't know it was so simple to fix.
