### ISSUE TITLE
No s3-endpoint option to use Openstack Swift

### ISSUE THREAD

**Issue by janibashamd** [danilop/yas3fs#151]
Hi Team,

I tried to use yas3fs to mount Swift3 bucket locally but found no S3-endpoint option in yas3fs manual. 
YAS3FS read me says this option is available. Please check and let me know if we can use S3 end-point other than AWS/GCP..

If yes, just let me know the steps.
FYI - I installed S3 middleware over Openstack Swift.

Thanks in advance.

**Comment by Liath** [comment]
Seems like you should be able to pass the endpoint as `--s3-endpoint url`. I have no way of testing this though, can you post an endpoint I can test against?

**Comment by dacut** [comment]
Looks like this has been solved. If not, please feel free to reopen.
