### ISSUE TITLE
Broken package in pypi

### ISSUE THREAD

**Issue by jnewbigin** [danilop/yas3fs#187]
Hi.
Been using yas3fs for a while now.
I can no longer pip install it on Python 2.7. That was always going to happen.
```
    Complete output from command python setup.py egg_info:
    pkg_resources/py2_warn.py:15: UserWarning: Setuptools no longer works on Python 2
    ************************************************************
    Encountered a version of Setuptools that no longer supports
    this version of Python. Please head to
    https://bit.ly/setuptools-py2-sunset for support.
    ************************************************************
```
But I can't pip install on Python 3.6 either.
```
...
    NameError: name 'execfile' is not defined
```

It looks like version 2.3.6 should work but pypi only has version 2.3.5.
https://pypi.org/search/?q=yas3fs

It is possible to get the new version published to pypi?

Thanks.

**Comment by jazzl0ver** [comment]
It's not longer available thru pip. The doc is outdated, use git clone instead
