### ISSUE TITLE
support for unicoded file names 

### ISSUE THREAD

**Issue by ewah** [danilop/yas3fs#56]
> mkdir £
> mkdir: cannot create directory `£': Bad address

encoding issues in lots of places. 

I am able to create these objects via AWS S3 console.

**Comment by gpiccinni** [comment]
Hi,
I've noticed that when using encoding_type='url' in s3 bucket list, boto does not return the list of all keys.
More precisely it stops at the first key which is not url encoded.
This causes yas3fs to do not list all files in a directory.

To run some tests you can create a file on s3 with symbol ° (degree sign) in the name and you try to list keys using boto, it won't return the file ( and all the other keys after the key with degree sign) if you use encoding_type='url' .

To fix it in yas3fs I've removed encoding_type='url' from __init__.py line 1692 and commented out line 1697 and in linux using ext4 it works as it also creates the file with this char.
