### ISSUE TITLE
Problem subscribing to SNS topic ARN

### ISSUE THREAD

**Issue by marcomagno** [danilop/yas3fs#76]
Hi Danilo,
we're having problems subscribing to our SNS ARN topic. We created a new topic in regione eu-west-1, configured its permission to "everyone" just to not have permission problems and then tried launching yas3fs. 

The command we're using is:
/usr/local/bin/yas3fs s3://[bucket] [mountpoint] --region eu-west-1 --topic [arn topic] --new-queue --hostname [ec2_hostname] -df

but we always get:
ERROR SNS topic ARN not found in region 'eu-west-1' , use -h for help.

If we launch yas3fs without --topic everything works.

Thanks,
Marco

**Comment by robmoore** [comment]
We're seeing something similar here. Did you ever work out the issue was?

**Comment by danilop** [comment]
I just did some tests with an SNS topic I already have and with a new topic I just created - both worked for me. Two things that are important when using SNS topics are:
1. you need to pass the full ARN of the topic to the --topic option, e.g. --topic arn:aws:sns:<region>:<account ID>:<topic name>
2. you need to specify the region of the SNS topic in the --region option
Can you please check that and let me know if that fixes? Thanks!

**Comment by robmoore** [comment]
@danilop Thanks! Throught trial and error I was able to figure out the need for the fully qualified topic name. Also, I may have neglected the region assuming us-east-1 would be the default (very US-centric of me, I realize). It might be helpful to supplement the documentation with this info.

**Comment by danilop** [comment]
I am happy you solved! The us-east-1 region is the default one, but the SNS
Topic ARN syntax requires the region to be part of it. I'll try to make it
more clear in the docs. Thanks fro your feedback!
