### ISSUE TITLE
is it possible to circumvent AWS Lambda limit of 512MB /tmp for larger S3 media files?

### ISSUE THREAD

**Issue by shafqatevo** [danilop/yas3fs#81]
Hi, we are considering using yas3fs from within Lambda to retrieve larger than 512 MB mp4 files from S3 but there is currently a limit of 512MB total file system space for all storage needs of the Lambda function. Is there any way to set parameters of the buffering and cache mechanism whereby ffmpeg can process the mp4 on the fly while reading and yas3fs can serve the larger-than-512MB file using no more than, let's say 400MB local storage space?

**Comment by bitsofinfo** [comment]
At this point that capability is not built in, and would require some significant changes to make that kind of behavior possible.

**Comment by shafqatevo** [comment]
If we completely disable the disk cache, would we be able to sequentially read an mp4 of 700MB start to end with a working memory of 1GB?

**Comment by bitsofinfo** [comment]
At this point I would suggest you simply try the configuration you just mentioned (no disk cache) to see how it will behave and report back. I have not tried that particular scenario.

**Comment by danilop** [comment]
Closing the issue at this point, but I am ready to open it again if more info are required.

**Comment by dustinkerstein** [comment]
@shafqatevo were you able to get ffmpeg working within lambda for larger files?

**Comment by vimmisinghani** [comment]
@bitsofinfo how to set no disk cache
