### ISSUE TITLE
Question: yas3fs limitations when used in non-EC2 or hybrid scenarios

### ISSUE THREAD

**Issue by Jaykah** [danilop/yas3fs#83]
Hi,

I am currently using "Azure Files" - an SMB-based solution to share files between a number of servers. Everything is working great, except I can only attach this storage to Azure servers (and they have to be in one region). Now, we have decided to expand our network to other VPS providers, such as AWS.
 
Looking for a solution that would allow us to share files between all of our servers (wherever they are hosted), I have stumbled upon yas3fs. So the plan is to store all files in S3, and mount the share to all servers via yas3fs.

Thus, I wanted to ask if there are any limitations to mounting/using yas3fs in non-EC2 environments (e.g. SQS not working, etc) prior to getting in too deep with this plan.

Thanks in advance.

**Comment by danilop** [comment]
Hi,

yas3fs works outside of EC2, e.g. I often use it on my mac, you just need Internet access to AWS APIs (S3, SNS, SQS). Outside of EC2 you cannot use IAM roles for authentication and you need AWS credentials on the node, so I'd create a IAM user with the least privileges and use its credentials.

Please test your workload with yas3fs to check it is compatible with your requirement. And share your use case on the wiki for future reference if you can/want/have time.

**Comment by Jaykah** [comment]
Sure, will do! Thanks!

**Comment by Jaykah** [comment]
Hi @danilop, one more question - is passing ENV variables the only way to supply credentials?

**Comment by bitsofinfo** [comment]
Yes that is the only way, feel free to submit a PR to provider another method if you wish

**Comment by Jaykah** [comment]
Sorry that I keep posting to a closed topic, but I think these questions belong here too:

1) For EC2 instances, do we subscribe our SQS queue to an appropriate SNS topic in AWS, or is it somehow handled by yas3fs at launch?

2) For non-AWS, I would assume we need to remove the --queue parameter and launch it with just the --topic and --port? And is --port not necessary for AWS endpoints?

**Comment by Jaykah** [comment]
Bump

**Comment by bitsofinfo** [comment]
Whether or not you configure yas3fs to use the SNS topic for broadcasting events, has nothing to do with where your instances lives. You can start yas3fs on ec2 nodes, azure nodes, your laptop, or your own vm's in your own data-center... etc. The SNS communication is just for yas3fs nodes to broadcast fs events to other yas3fs nodes (regardless of where they physically reside).
