### ISSUE TITLE
read 2048 and also "no range"

### ISSUE THREAD

**Issue by bradspry** [danilop/yas3fs#84]
I've observed read calls happening in 2048k; is that an adjustable variable?

I've experimented with --st-blksize, but I believe it's only applicable to getattr() callers, just like the documentation says.

Also, noticed lines with each read call with "no range" appended:

2015-03-09 17:11:17,543 DEBUG read '/datastreamStore/1e/info%3Afedora%2Fmighty%3A1%2FMEDIUM%5FSIZE%2FMEDIUM%5FSIZE.0' '2048' '363667' '0'
2015-03-09 17:11:17,543 DEBUG read '/datastreamStore/1e/info%3Afedora%2Fmighty%3A1%2FMEDIUM%5FSIZE%2FMEDIUM%5FSIZE.0' '2048' '363667' '0' no range

Is there anything else I can configure to improve read performance?

Thank You ahead of time!

**Comment by bitsofinfo** [comment]
See https://github.com/danilop/yas3fs/issues/43

Its totally up to the calling program as to what block size it will read with

**Comment by bradspry** [comment]
Thanks for pointing out #43; I had read it numerous times but I completely failed to grasp:

"Whether or not it will have an effect on a "caller" (writer) is up to the caller, for example CP seems to increase its write block size when this is set, but some other programs do not."

Please close this issue at your earliest convenience.

Thanks Again!

Brad
