### ISSUE TITLE
How to update yas3fs inode table after  "aws s3 sync" or "s3cmd sync"

### ISSUE THREAD

**Issue by alexg-eslevier** [danilop/yas3fs#87]
Good day
thank you for yas3fs filesystem and your help
I am novice in yas3fs and performing tests on migration from EBS to S3 
Our filesystem atop of S3 is yas3fs

I noticed that after running  "aws s3 sync" or "s3cmd sync" against S3 bucket
yas3fs does not recognize new/deleted files.
I can not unmount and remount yas3fs filesystem each time after running sync, it will be a life filesystem,

so I did mount it again atop of existing mount
"/usr/bin/yas3fs  --nonempty --recheck-s3" and that allowed for yas3fs to see new files

Question: is it safe to do it and is there other way to update files list?

Thank you

**Comment by bitsofinfo** [comment]
Files manipulated in the bucket outside of a yas3fs cluster will not "notify" yas3fs of any new items in S3. You will either have to

- stop yas3fs, clear cache, restart it

- or write your own code that will publish change messages to yas3fs sns topic, as your other application makes changes

If you mount it again, I'd be careful that both yas3fs processes use separate cache directories

**Comment by alexg-eslevier** [comment]
Thank you so much for quick reply

May I ask what is the safest way to clear cache after stopping yas3fs?

**Comment by bitsofinfo** [comment]
I generally just wipe the contents of the cache directory, i.e. just rm -rf it

**Comment by alexg-eslevier** [comment]
Thank you very much!
