### ISSUE TITLE
SNS Sync not working on Ubuntu

### ISSUE THREAD

**Issue by Jaykah** [danilop/yas3fs#91]
Hi,

I have encountered a strange error when trying to get yas3fs to work in a non-AWS environment.

```
2015-04-07 22:04:45,743 DEBUG downloading certificate
----------------------------------------
Exception happened during processing of request from ('72.21.217.122', 21857)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/usr/local/lib/python2.7/dist-packages/yas3fs/__init__.py", line 614, in do_POST
    cert = M2Crypto.X509.load_cert_string(self.certificate)
NameError: global name 'M2Crypto' is not defined
----------------------------------------
^C2015-04-07 22:07:02,420 DEBUG destroy '/'
2015-04-07 22:07:02,421 INFO File system unmount...
2015-04-07 22:07:02,421 DEBUG flush_all_cache
2015-04-07 22:07:02,422 INFO waiting for SNS publish thread to shutdown...
2015-04-07 22:07:02,536 INFO waiting for check cache thread to shutdown...
2015-04-07 22:07:05,608 INFO File system unmounted.
```

But the package is already installed:

```
root:/mnt# pip install m2crypto
Requirement already satisfied (use --upgrade to upgrade): m2crypto in /usr/local/lib/python2.7/dist-packages
Cleaning up...
```

Am I missing something?

**Comment by Jaykah** [comment]
Further troubleshooting leads to the necessity to do

```
cd /usr/include/openssl/ && ln -s ../x86_64-linux-gnu/openssl/opensslconf.h .
```

and then install M2Crypto again...

```
wget http://chandlerproject.org/pub/Projects/MeTooCrypto/M2Crypto-0.21.1-py2.7-macosx-10.8-intel.egg && sudo easy_install M2Crypto-*.egg
```

however, that leads us to

```
2015-04-07 22:18:12,186 ERROR Uncaught Exception: <type 'exceptions.ImportError'> /root/.python-eggs/M2Crypto-0.21.1-py2.7-linux-x86_64.egg-tmp/M2Crypto/__m2crypto.so: undefined symbol: SSLv2_method <traceback object at 0x7f8a4bd636c8>
None
````

which looks like this bug https://github.com/saltstack/salt/issues/391

**Comment by Jaykah** [comment]
And going with the default ubuntu python-m2crypto package brings us back to

```
NameError: global name 'M2Crypto' is not defined
```

**Comment by Jaykah** [comment]
I have tried manually patching M2Crypto to remove SSLv2, no avail.

https://github.com/martinpaljak/M2Crypto/commit/84977c532c2444c5487db57146d81bb68dd5431d here as well,

**Comment by danilop** [comment]
I always preferred the SQS pull model (from the client environment) to SNS push for this kind of use case. Is there any blocker to not use SQS in this case? I implemented SNS push (via HTTP) when SQS didn't have long polling, but since it was released I never used SNS with yas3fs. What do you think?

**Comment by Jaykah** [comment]
Most of my nodes are non-AWS. Correct me if I'm wrong, but I thought I cannot use SQS for those endpoints.

**Comment by bitsofinfo** [comment]
Whether or not you configure yas3fs to use the SNS topic for broadcasting events, has nothing to do with where your instances lives. You can start yas3fs on ec2 nodes, azure nodes, your laptop, or your own vm's in your own data-center... etc. The SNS communication is just for yas3fs nodes to broadcast fs events to other yas3fs nodes (regardless of where they physically reside).

**Comment by Jaykah** [comment]
Thanks, will try it.

**Comment by Jaykah** [comment]
I understand that, but am new to AWS and not quite sure of how the difference between SNS and SQS mechanisms would impact yas3fs config. 

So, regardless of whether we are using SNS or SQS we will have to supply "--port", but in the case of an AWS endpoint we can use "--use-ec2-hostname" instead of "--hostname" (which is also needed for non-AWS)?

**Comment by Jaykah** [comment]
Ok, so I think I got it working with --queue and --topic but without --hostname and --port. I assume those two are not necessary?

**Comment by danilop** [comment]
Yes, great work! Those parameters are for SNS HTTP notifications only, not required if using SQS.

dp

**Comment by Jaykah** [comment]
Thank you!
