### ISSUE TITLE
Slow read performance

### ISSUE THREAD

**Issue by dpwrussell** [danilop/yas3fs#98]
I have just been checking out yas3fs as I thought it might be useful in my application.

FYI: S3 and EC2 where I ran my tests are both in the same region.

The first test I did was to mount one of my buckets and then attempt to do an operation (sha1 in this case) on that file. The file was ~850MB in size and I was expecting there to be a delay on the first run because the file would need to be downloaded. That turned out to be the case, but wildly more than I was expecting.

```
$ time sha1sum 03302014-r1.nd.ome.tif
efebdfcd4241fb53fc8f04d31897970db21bdca1  03302014-r1.nd.ome.tif

real	2m9.312s
user	0m2.448s
sys	0m1.318s
```

I thought that was rather a long time as I can download this file from s3 to this EC2 instance in ~15s usually. Anyway, I thought I'd then repeat the experiment to see how it performed once the file has been cached locally. I was surprised that the result was not a lot better which I guess points to the overhead of yas3fs/FUSE as the problem.

```
$ time sha1sum 03302014-r1.nd.ome.tif
efebdfcd4241fb53fc8f04d31897970db21bdca1  03302014-r1.nd.ome.tif

real	1m40.551s
user	0m2.568s
sys	0m1.245s
```

Just in case something weird was happening in the case of calculating the sha1, I also tried a basic copy operation (to a non s3 location):

```
$ time cp 03302014-r1.nd.ome.tif ~/

real	1m37.469s
user	0m0.002s
sys	0m1.280s
```

Also for reference, this is how long it takes to calculate the sha1 from the cached file:

```
$ time sha1sum /tmp/yas3fs/dpwr/files/s3test/03302014-r1.nd.ome.tif
efebdfcd4241fb53fc8f04d31897970db21bdca1  /tmp/yas3fs/dpwr/files/s3test/03302014-r1.nd.ome.tif

real	0m2.890s
user	0m2.793s
sys	0m0.099s
```

Is this likely to be a bug or is that the expected performance of FUSE and/or S3 based filesystems? I don't have any previous experience with either and I'm trying to figure out the best avenue to explore for my application.

Thanks a lot,

Douglas

**Comment by bitsofinfo** [comment]
see #44, #64, #43

**Comment by dpwrussell** [comment]
Ah, that's too bad. Thanks for the response.
