### ISSUE TITLE
Directory not updating

### ISSUE THREAD

**Issue by davidkelley** [danilop/yas3fs#99]
Hi, I'm on OS X and after following the getting started guide I have successfully mounted a directory and connected it to an existing S3 Bucket using the basic `yas3fs s3://bucket/path /path/to/mount --no-metadata` command. It has retrieved the contents of the bucket and the directory is populated.

However, the directory is not "updating" to reflect changes to the contents of the S3 bucket. As files are added/removed the contents of the local directory remain the same as when the command was first ran.

Am I doing something wrong, or?

**Comment by danilop** [comment]
Hi David, this is the correct behavior.

Yas3fs was designed to cache everything locally, before S3 notifications,
so it is sending/receiving its own notifications when somethings has
changed through the file system - but this notifications are produced by
nodes using yas3fs, not by S3 itself.

Now S3 can send events for changes, but only for new/updated objects, not
for deletions. If someone volunteers to include this support into yas3fs,
she/he is welcome.

You may have also a look at other S3 FUSE File Systems implementations that
don't cache locally as yas3fs does, if you need a different behavior.

Best,
dp

**Comment by davidkelley** [comment]
Hi @danilop , thanks for getting back to me. I'll take a look at the code and see if I can figure it out.

It also looks like AWS have implemented support for [Delete notifications](https://aws.amazon.com/blogs/aws/amazon-s3-update-delete-notifications-better-filters-bucket-metrics/) now too.

**Comment by danilop** [comment]
Yes! Delete notifications was announced yesterday, just after my comment :)
